### ISSUE TITLE
Meta: Translations

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms-django#104]
This is a meta issue with links to all Translations issues:
* [x] #38 Import XLIFF
* [x] #37 Export XLIFF
* [x] #85 Translation side-by-side view
* [x] #84 Export pages
* [x] #83 Status icons
* [x] #9 Translation coverage analytics
* [x] #155 Tab view for different languages
* [x] #156 Review workflow

**Comment by timoludwig** [comment]
- Language Management: LanguageTree to List
- One translator per page
- One origin language per page translation (null for default language)

**Comment by svenseeberg** [comment]
Candidates:

* https://pypi.org/project/django-xliff/ / https://github.com/callowayproject/django-xliff
* https://pypi.org/project/slc.xliff/ / https://github.com/collective/slc.xliff
* https://pypi.org/project/py-xliff-converter / https://github.com/romanvm/py-xliff-converter

**Comment by timoludwig** [comment]
Ok. Another option might be https://pypi.org/project/django-modeltranslation-xliff/ / https://github.com/romanvm/django-modeltranslation-xliff, but I don't know if we can use this outside the standard django admin backend.

**Comment by svenseeberg** [comment]
The Expedia team noticed that the django-modelstranslations is bound to the back end languages defined in the settings.py. Because our content languages are independent of the UI languages, we need our own implementation for exporting into XLIFF files. But we can copy functions for generating XLIFF files from existing modules to speed up the development.

**Comment by svenseeberg** [comment]
I remove `#36 Automatic translation API (DeepL, Google) (Additional Features)` from this meta issue. I don't see this as part of it right now.
